"""create loads carriers calls offers

Revision ID: 747ddda7afe0
Revises: 
Create Date: 2026-04-21 18:29:59.260723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747ddda7afe0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_call_id', sa.String(length=128), nullable=True),
    sa.Column('mc_number', sa.String(length=16), nullable=True),
    sa.Column('carrier_name', sa.String(length=255), nullable=True),
    sa.Column('load_reference_number', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.Column('final_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('loadboard_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rounds_used', sa.Integer(), nullable=True),
    sa.Column('agreement_reached', sa.Boolean(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('extracted_fields', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_external_call_id'), 'calls', ['external_call_id'], unique=False)
    op.create_index(op.f('ix_calls_load_reference_number'), 'calls', ['load_reference_number'], unique=False)
    op.create_index(op.f('ix_calls_mc_number'), 'calls', ['mc_number'], unique=False)
    op.create_index(op.f('ix_calls_outcome'), 'calls', ['outcome'], unique=False)
    op.create_index(op.f('ix_calls_sentiment'), 'calls', ['sentiment'], unique=False)
    op.create_table('carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mc_number', sa.String(length=16), nullable=False),
    sa.Column('dot_number', sa.String(length=16), nullable=True),
    sa.Column('carrier_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('allowed_to_operate', sa.Boolean(), nullable=False),
    sa.Column('fmcsa_raw', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carriers_dot_number'), 'carriers', ['dot_number'], unique=False)
    op.create_index(op.f('ix_carriers_mc_number'), 'carriers', ['mc_number'], unique=True)
    op.create_table('loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('equipment_type', sa.String(length=32), nullable=False),
    sa.Column('commodity_type', sa.String(length=64), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('is_hazmat', sa.Boolean(), nullable=False),
    sa.Column('posted_carrier_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_buy', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('number_of_pieces', sa.Integer(), nullable=True),
    sa.Column('miles', sa.Integer(), nullable=True),
    sa.Column('dimensions', sa.String(length=64), nullable=True),
    sa.Column('sale_notes', sa.Text(), nullable=True),
    sa.Column('origin_city', sa.String(length=64), nullable=False),
    sa.Column('origin_state', sa.String(length=16), nullable=False),
    sa.Column('origin_zip', sa.String(length=16), nullable=False),
    sa.Column('origin_country', sa.String(length=8), nullable=False),
    sa.Column('origin_open', sa.DateTime(), nullable=False),
    sa.Column('origin_close', sa.DateTime(), nullable=False),
    sa.Column('destination_city', sa.String(length=64), nullable=False),
    sa.Column('destination_state', sa.String(length=16), nullable=False),
    sa.Column('destination_zip', sa.String(length=16), nullable=False),
    sa.Column('destination_country', sa.String(length=8), nullable=False),
    sa.Column('destination_open', sa.DateTime(), nullable=False),
    sa.Column('destination_close', sa.DateTime(), nullable=False),
    sa.Column('contact', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loads_destination_city'), 'loads', ['destination_city'], unique=False)
    op.create_index(op.f('ix_loads_destination_state'), 'loads', ['destination_state'], unique=False)
    op.create_index(op.f('ix_loads_equipment_type'), 'loads', ['equipment_type'], unique=False)
    op.create_index(op.f('ix_loads_origin_city'), 'loads', ['origin_city'], unique=False)
    op.create_index(op.f('ix_loads_origin_state'), 'loads', ['origin_state'], unique=False)
    op.create_index(op.f('ix_loads_reference_number'), 'loads', ['reference_number'], unique=True)
    op.create_index(op.f('ix_loads_status'), 'loads', ['status'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('mc_number', sa.String(length=16), nullable=False),
    sa.Column('load_reference_number', sa.String(length=64), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('carrier_offer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('agent_counter', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_call_id'), 'offers', ['call_id'], unique=False)
    op.create_index(op.f('ix_offers_load_reference_number'), 'offers', ['load_reference_number'], unique=False)
    op.create_index(op.f('ix_offers_mc_number'), 'offers', ['mc_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_mc_number'), table_name='offers')
    op.drop_index(op.f('ix_offers_load_reference_number'), table_name='offers')
    op.drop_index(op.f('ix_offers_call_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_loads_status'), table_name='loads')
    op.drop_index(op.f('ix_loads_reference_number'), table_name='loads')
    op.drop_index(op.f('ix_loads_origin_state'), table_name='loads')
    op.drop_index(op.f('ix_loads_origin_city'), table_name='loads')
    op.drop_index(op.f('ix_loads_equipment_type'), table_name='loads')
    op.drop_index(op.f('ix_loads_destination_state'), table_name='loads')
    op.drop_index(op.f('ix_loads_destination_city'), table_name='loads')
    op.drop_table('loads')
    op.drop_index(op.f('ix_carriers_mc_number'), table_name='carriers')
    op.drop_index(op.f('ix_carriers_dot_number'), table_name='carriers')
    op.drop_table('carriers')
    op.drop_index(op.f('ix_calls_sentiment'), table_name='calls')
    op.drop_index(op.f('ix_calls_outcome'), table_name='calls')
    op.drop_index(op.f('ix_calls_mc_number'), table_name='calls')
    op.drop_index(op.f('ix_calls_load_reference_number'), table_name='calls')
    op.drop_index(op.f('ix_calls_external_call_id'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
